[package]
name = "faker_boy"
version = "0.1.0"
edition = "2021"

[dependencies]
uuid = { workspace = true }
thiserror = { workspace = true }
utils = { path = "../utils" }
tokio = { workspace = true }
dirs = { workspace = true }


[build-dependencies]
embed-resource = "2.4.3"

[[bin]]
name = "faker_boy"
path = "src/main.rs"
