[package]
name = "utils"
version = "0.1.0"
edition = "2021"

[lib]
crate-type = ["lib"]

[dependencies]
uuid = { workspace = true }
thiserror = { workspace = true }
egui = "0.28.1"
walkdir = "2.5.0"
dirs = "5.0.1"

aes-gcm = "0.10.3"
aes-gcm-siv = "0.11.1"